services:
  excel2json-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: excel2json-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    command: npm run dev
    restart: unless-stopped
    networks:
      - excel2json-dev-network

networks:
  excel2json-dev-network:
    driver: bridge
    name: excel2json-dev-network